# Default training configuration for fixed-wing UAV route planning
algorithm:
  name: ppo
  total_timesteps: 200000
  device: cuda
  policy_kwargs: {}

wind_field:
  era5_path: ""
  u_component: u10
  v_component: v10
  w_component: w
  altitude: level

environment:
  initial_latitude: 34.5
  initial_longitude: -117.5
  initial_altitude_m: 1500.0
  target:
    latitude: 34.8
    longitude: -117.2
    altitude: 1600.0
  max_time_s: 900
  dt: 0.02
  cruise_speed_mps: 40.0
  energy_weight: 0.01
  time_weight: 1.0
  stability_weight: 0.5
  max_roll_deg: 45.0
  max_pitch_deg: 20.0
  max_throttle: 1.0
  aircraft: c172x
  jsbsim_root: null
  max_wind_speed_ms: 12.0

evaluation:
  steps: 2000

output:
  model_dir: checkpoints
  plots_dir: plots
  tensorboard_log: logs
